name: "Build on push to main"

on: pull_request:
      branches:
        - main
    push:
      branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Install Dependencies for backend
        run: cd backend && npm i && npm run dev
      - name: Install Dependencies for frontend
        run: cd frontend && npm i && npm run build
     
